main: 'org.burrow_studios.spigot.statusplugin.Main'
name: 'StatusPlugin'
version: '${project.version}'
api-version: '1.20'
authors:
  - bySleax
  - TurtleException
website: 'https://github.com/BurrowStudios/StatusPlugin'
commands:
  status:
    usage: '/status <status>'
    description: 'Changes your player status.'